### ISSUE TITLE
Very good work

### ISSUE THREAD

**Issue by Coder-Yu** [noveens/distill_cf#3]
Hi Noveens,

DistillCF is a great work. I am also working on the data distillation these days. I came across your paper a few months ago but did not read it. Recently I have been developing my model and then I read it today. Can't believe the technical details in your paper are almost as the same as my design (using multi-round gumbel-softmax to generate discrete values and L1 regularization to meet the budget). Even the experiments and the emphasis on data-centric methods in your paper are similar to my plan. What a coincidence! 😆

It looks like I have to re-design my model from some new perspectives. Thank you for your contributions on data distillation.  I also like the infinite-AE part👍

**Comment by noveens** [comment]
Sent you a DM! Thanks for your nice comment :)
